### ISSUE TITLE
hubot startup error

### ISSUE THREAD

**Issue by sajeeshgit** [hubotio/hubot#1465]
Error: Cannot find module '..'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:289:25)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Object.<anonymous> (/app/node_modules/public/node_modules/.bin/hubot:5:12, <js>:4:11)
  at Object.<anonymous> (/app/node_modules/public/node_modules/.bin/hubot:5:1, <js>:185:4)
  at Module._compile (module.js:435:26)
  at Object.exports.run (/app/node_modules/public/node_modules/hubot/node_modules/lib/coffee-script/coffee-script.js:103:25)
  at compileScript (/app/node_modules/public/node_modules/hubot/node_modules/lib/coffee-script/command.js:171:29)
  at /app/node_modules/public/node_modules/hubot/node_modules/lib/coffee-script/command.js:143:18
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

**Comment by jaythomas** [comment]
Can you provide more information on how this error can be reproduced? For instance, what scripts/plugins you are using?

**Comment by joh6nn** [comment]
It's been 5 years, I'm going to go ahead and close this out
