### ISSUE TITLE
Recommended Heroku Deploy Not Working

### ISSUE THREAD

**Issue by william-bratches** [hubotio/hubot#1537]
Getting a near-default hubt up and running quickly with heroku yields the following:

```
/tmp/build_98cfa1dd4cdc4c9b4af155631ee1d3db/.heroku/node/lib/node_modules/npm/bin/npm-cli.js:79

      var notifier = require('update-notifier')({pkg})

                                                    ^

SyntaxError: Unexpected token }

    at Module._compile (module.js:439:25)

    at Object.Module._extensions..js (module.js:474:10)

    at Module.load (module.js:356:32)

    at Function.Module._load (module.js:312:12)

    at Function.Module.runMain (module.js:497:10)

    at startup (node.js:119:16)

    at node.js:945:3

-----> Build failed
```

Steps to reproduce:

Follow the hubot getting started instructions (https://hubot.github.com/docs/)

**Comment by william-bratches** [comment]
This turned out to be very outdated node engine limit in the default yo-generated `package.json`.
