### ISSUE TITLE
Pushing hubot to heroku

### ISSUE THREAD

**Issue by ghost** [hubotio/hubot#584]
I am trying to push Hubot to a herokuapp, so I can have my own cool robot, but when I try to push to heroku, this happens: 

```
2013-09-16T20:28:41.845458+00:00 heroku[web.1]: State changed from crashed to starting
2013-09-16T20:28:46.148520+00:00 heroku[web.1]: State changed from starting to up
2013-09-16T20:28:48.499369+00:00 heroku[web.1]: State changed from up to crashed
2013-09-16T20:28:51.195477+00:00 heroku[api]: Add HEROKU_URL config by darkbladeftw@gmail.com
2013-09-16T20:28:51.241895+00:00 heroku[api]: Release v8 created by darkbladeftw@gmail.com
2013-09-16T20:28:51.356638+00:00 heroku[web.1]: State changed from crashed to starting
2013-09-16T20:28:53.613616+00:00 heroku[web.1]: Starting process with command `bin/hubot -a campfire -n Hubot`
2013-09-16T20:28:54.412529+00:00 app[web.1]: bin/hubot: 3: npm: not found
2013-09-16T20:28:55.616620+00:00 heroku[web.1]: State changed from starting to up
2013-09-16T20:28:56.307124+00:00 app[web.1]: [Mon Sep 16 2013 20:28:56 GMT+0000 (UTC)] WARNING The HUBOT_AUTH_ADMIN environment variable not set
2013-09-16T20:28:58.150284+00:00 app[web.1]: [Mon Sep 16 2013 20:28:58 GMT+0000 (UTC)] ERROR [Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED]
2013-09-16T20:28:58.343971+00:00 app[web.1]: [Mon Sep 16 2013 20:28:58 GMT+0000 (UTC)] ERROR Campfire error: 404
2013-09-16T20:28:58.347083+00:00 app[web.1]: 
2013-09-16T20:28:58.354111+00:00 app[web.1]: /app/node_modules/hubot/src/adapters/campfire.coffee:160
2013-09-16T20:28:58.354465+00:00 app[web.1]:         bot.name = bot.info.name;
2013-09-16T20:28:58.355656+00:00 app[web.1]:                            ^
2013-09-16T20:28:58.387514+00:00 app[web.1]: TypeError: Cannot read property 'name' of undefined
2013-09-16T20:28:58.387514+00:00 app[web.1]:   at IncomingMessage.<anonymous> (/app/node_modules/hubot/src/adapters/campfire.coffee:293:13, <js>:393:22)
2013-09-16T20:28:58.387514+00:00 app[web.1]:   at _stream_readable.js:920:16
2013-09-16T20:28:58.387514+00:00 app[web.1]:   at process._tickCallback (node.js:415:13)
2013-09-16T20:28:58.387514+00:00 app[web.1]: 
2013-09-16T20:28:58.387514+00:00 app[web.1]:   at /app/node_modules/hubot/src/adapters/campfire.coffee:101:7, <js>:160:28
2013-09-16T20:28:58.387514+00:00 app[web.1]:   at IncomingMessage.EventEmitter.emit (events.js:117:20)
2013-09-16T20:29:00.231647+00:00 heroku[web.1]: Process exited with status 8
2013-09-16T20:29:00.248728+00:00 heroku[web.1]: State changed from up to crashed
2013-09-16T20:29:06.202707+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path=/ host=intense-taiga-7478.herokuapp.com fwd="69.159.45.248" dyno= connect= service= status=503 bytes=
2013-09-16T20:29:06.445057+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path=/favicon.ico host=intense-taiga-7478.herokuapp.com fwd="69.159.45.248" dyno= connect= service= status=503 bytes=
2013-09-16T20:29:08.294029+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path=/ host=intense-taiga-7478.herokuapp.com fwd="69.159.45.248" dyno= connect= service= status=503 bytes=
2013-09-16T20:29:09.053927+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path=/favicon.ico host=intense-taiga-7478.herokuapp.com fwd="69.159.45.248" dyno= connect= service= status=503 bytes=
2013-09-16T20:29:11.051239+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path=/ host=intense-taiga-7478.herokuapp.com fwd="69.159.45.248" dyno= connect= service= status=503 bytes=
2013-09-16T20:29:12.973562+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path=/favicon.ico host=intense-taiga-7478.herokuapp.com fwd="69.159.45.248" dyno= connect= service= status=503 bytes=
2013-09-16T20:29:07.961054+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path=/favicon.ico host=intense-taiga-7478.herokuapp.com fwd="69.159.45.248" dyno= connect= service= status=503 bytes=
2013-09-16T20:29:12.299090+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path=/ host=intense-taiga-7478.herokuapp.com fwd="69.159.45.248" dyno= connect= service= status=503 bytes=
2013-09-16T20:29:12.458673+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path=/favicon.ico host=intense-taiga-7478.herokuapp.com fwd="69.159.45.248" dyno= connect= service= status=503 bytes=
2013-09-16T20:29:11.673237+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path=/ host=intense-taiga-7478.herokuapp.com fwd="69.159.45.248" dyno= connect= service= status=503 bytes=
2013-09-16T20:29:12.807894+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path=/ host=intense-taiga-7478.herokuapp.com fwd="69.159.45.248" dyno= connect= service= status=503 bytes=
```

Any help please? I would love to have my own bot to boss around!

**Comment by JPomichael** [comment]
i used https://github.com/github/hubot/blob/master/docs/adapters/campfire.md#configuring-the-variables-on-windows

```
$ bin/hubot
Hubot> [Tue Nov 24 2015 13:43:01 GMT+0800 (中国标准时间)] ERROR hubot-heroku-alive included,    but missing HUBOT_HEROKU_KEEPALIVE_URL. `heroku config:set HUBOT_HEROKU_KEEPALIVE_URL=$(heroku apps:info -s  | grep web_url | cut -d= -f2)`
[Tue Nov 24 2015 13:43:01 GMT+0800 (中国标准时间)] INFO hubot-redis-brain: Using default redis on localhost:6379
```
